[package]
name = "fundable"
version = "0.1.0"
edition = "2023_11"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
openzeppelin = "1.0.0"
starknet = "2.11.2"

[profile.dev.cairo]
unstable-add-statements-code-locations-debug-info = true
unstable-add-statements-functions-debug-info = true

[dev-dependencies]
snforge_std = "0.40.0"
assert_macros = "2.11.2"

[[target.starknet-contract]]
casm = true
sierra = true

[scripts]
test = "SNFORGE_BACKTRACE=1 snforge test"

[tool.scarb]
allow-prebuilt-plugins = ["snforge_std"]

[[tool.snforge.fork]]
name = "MAINNET"
url = "https://starknet-mainnet.public.blastapi.io/rpc/v0_7"
block_id.number = "1173917"

[tool.snforge]
fuzzer_runs = 10